// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orwdocowrajhmryaxjvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yd2RvY293cmFqaG1yeWF4anZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjQ2MTEsImV4cCI6MjA2OTkwMDYxMX0.Fof7AZOzkysZuYdmFkyxSeWPkBxxF_8a07Zbjbx5neg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});